export enum StripePaymentStatus{
  PAID="PAID",
  UNPAID="UNPAID",
  NO_PAYMENT_REQUIRED="NO_PAYMENT_REQUIRED",  
}

export enum PrescriptionStatus{
   PENDING="PENDING",
  APPROVED="APPROVED",
  REJECTED="REJECTED",
  USED="USED",
  EXPIRED="EXPIRED"
}

export enum OrderStatus {
  PENDING="PENDING",
  CONFIRMED="CONFIRMED",
  SHIPPED="SHIPPED",
  DELIVERED="DELIVERED",
  CANCELLED="CANCELLED"
}