export enum PaymentStatus{
 PENDING="PENDING",
  SUCCESS="SUCCESS",
  FAILED="FAILED",
  REFUNDED="REFUNDED"
}

export enum PrescriptionStatus{
   PENDING="PENDING",
  APPROVED="APPROVED",
  REJECTED="REJECTED",
  USED="USED",
  EXPIRED="EXPIRED"
}

export enum OrderStatus {
  PENDING="PENDING",
  CONFIRMED="CONFIRMED",
  SHIPPED="SHIPPED",
  DELIVERED="DELIVERED",
  CANCELLED="CANCELLED"
}